version: 2
updates:
  - commit-message:
      prefix: "Changelog:All"
    directory: /tests/acceptance
    package-ecosystem: pip
    schedule:
      interval: weekly
  - commit-message:
      prefix: "Changelog:All"
    directory: /meta-mender-qemu/docker/qemux86-64
    package-ecosystem: docker
    schedule:
      interval: weekly
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
    target-branch: "master"
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
    target-branch: "zeus"
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
    target-branch: "dunfell"
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
    target-branch: "gatesgarth"
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
    target-branch: "hardknott"

