version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /tests/acceptance
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
  - commit-message:
      prefix: chore
    directory: /meta-mender-qemu/docker/qemux86-64
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    target-branch: master
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    target-branch: dunfell
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    target-branch: kirkstone
