version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /tests/acceptance
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
    groups:
      python-test-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /meta-mender-qemu/docker/qemux86-64
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    target-branch: master
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    target-branch: scarthgap
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    target-branch: kirkstone
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
